language: python
python:
  - '3.6.7'
install: 
  - pip install -r requirements.txt
  - pip install coveralls codecov
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE ireporter;" -U postgres
  
script: 
  - pytest --cov-report term-missing --cov app
  
after_success:
  - coveralls
  - codecov --token=3eb6f3bc-16a6-442a-84e1-acb108cbbb2c
  
cache: pip
